# Generated by Django 3.1 on 2022-06-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choises',
            old_name='image_choice_src',
            new_name='image_choise_src',
        ),
    ]
