# Generated by Django 3.1 on 2022-06-29 15:35

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choises',
            options={'ordering': ['created_at'], 'verbose_name': 'Choises'},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['created_at'], 'verbose_name': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='choises',
            name='audio_src_choise',
            field=models.FileField(null=True, upload_to=api.models.upload_audio_choice_path, validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='音声ファイル'),
        ),
        migrations.AlterField(
            model_name='choises',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choises', to='api.quizzes'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='audio_src_question',
            field=models.FileField(null=True, upload_to=api.models.upload_audio_question_path, validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='音声ファイル'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='image_src',
            field=models.ImageField(null=True, upload_to=api.models.upload_image_question_path),
        ),
    ]
