# Generated by Django 3.1 on 2022-06-30 08:50

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220630_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choises',
            name='audio_choise_src',
            field=models.FileField(null=True, upload_to=api.models.upload_audio_choice_path, validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='選択肢音声ファイル'),
        ),
        migrations.AlterField(
            model_name='choises',
            name='image_choise_src',
            field=models.ImageField(null=True, upload_to=api.models.upload_image_choise_path, verbose_name='選択肢画像ファイル'),
        ),
    ]
